# Generated by Django 2.2.5 on 2019-09-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('serie', models.CharField(max_length=100, verbose_name='Série')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
            ],
            options={
                'db_table': 'autor',
            },
        ),
    ]
