# Generated by Django 2.2.6 on 2019-10-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='tipo',
            field=models.CharField(choices=[(0, 'Orientador'), (1, 'Estudante')], max_length=10),
        ),
    ]
