# Generated by Django 2.2.7 on 2019-11-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='instituicao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
