# Generated by Django 2.2.5 on 2019-09-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table=None,
        ),
    ]
