# Generated by Django 2.2.7 on 2019-11-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20191117_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='name',
            new_name='nome',
        ),
    ]
