# Generated by Django 2.2.7 on 2019-11-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20191119_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='idade',
        ),
        migrations.AddField(
            model_name='autor',
            name='dt_nasc',
            field=models.DateField(default=None, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='instituicao',
            field=models.CharField(max_length=100, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='tipo',
            field=models.CharField(choices=[('E', 'Estudante'), ('O', 'Orientador')], max_length=100),
        ),
    ]
