# Generated by Django 2.2.5 on 2019-09-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20190930_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
