# Generated by Django 2.2.6 on 2019-10-22 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20191022_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[(0, 'Ciências'), (1, 'Exatas')], max_length=10)),
                ('palavras_chave', models.CharField(max_length=30)),
                ('plano_pesquisa', models.FileField(upload_to='uploads/')),
                ('link_video', models.CharField(max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
