# Generated by Django 2.2.7 on 2019-11-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_auto_20191119_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='dt_nasc',
            field=models.DateField(default=None, help_text='Por favor use o seguinte formato: YYYY-MM-DD', verbose_name='Data de Nascimento'),
        ),
    ]
