# Generated by Django 2.2.5 on 2019-09-30 19:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_autor'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='autor',
            managers=[
                ('objectos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='autor',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='autor',
            name='curso',
            field=models.CharField(default=True, max_length=100, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(default=True, max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='autor',
            name='idade',
            field=models.IntegerField(default=True, verbose_name='Idade'),
        ),
        migrations.AddField(
            model_name='autor',
            name='instituicao',
            field=models.CharField(default=True, max_length=100, verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='autor',
            name='serie',
            field=models.CharField(default=True, max_length=100, verbose_name='Série'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(default=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterModelTable(
            name='autor',
            table='autor',
        ),
    ]
