# Generated by Django 2.2.6 on 2019-10-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='area',
            field=models.CharField(max_length=10),
        ),
    ]
