# Generated by Django 2.2.7 on 2019-11-21 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_auto_20191119_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
