# Generated by Django 2.2.7 on 2019-11-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_autor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='user',
        ),
    ]
