# Generated by Django 2.2.5 on 2019-10-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_auto_20190930_1646'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='autor',
            managers=[
            ],
        ),
    ]
