# Generated by Django 2.2.7 on 2019-11-22 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_remove_autor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='tipo',
        ),
        migrations.AddField(
            model_name='autor',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Orientador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('instituicao', models.CharField(max_length=100, verbose_name='Instituição')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orientador',
                'verbose_name_plural': 'Orientadores',
            },
        ),
    ]
