# Generated by Django 2.2.6 on 2019-10-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20191026_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='area',
            field=models.CharField(choices=[('CHL', 'Ciências Humanas e Linguagens'), ('CNE', 'Ciências da Natureza e Exatas'), ('I', 'Informática'), ('E', 'Engenharias')], max_length=100),
        ),
    ]
