# Generated by Django 2.2.6 on 2019-10-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_auto_20191001_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AddField(
            model_name='autor',
            name='tipo',
            field=models.CharField(choices=[(0, 'Orientador'), (1, 'Estudante')], default=0, max_length=10),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[(0, 'Ciências Humanas e Linguagens'), (1, 'Ciências da Natureza e Exatas'), (2, 'Informática'), (3, 'Engenharias')], max_length=32)),
                ('palavras_chaves', models.CharField(max_length=100)),
                ('plano_de_pesquisa', models.FileField(upload_to='uploads/')),
                ('link_video', models.CharField(max_length=150)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Autor')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'projeto',
            },
        ),
    ]
