# Generated by Django 2.2.7 on 2019-11-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20191026_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='tipo',
            field=models.CharField(choices=[('E', 'Estudante')], max_length=100),
        ),
    ]
