# Generated by Django 2.2.7 on 2019-11-27 01:26

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20191126_2209'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='autor',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orientador',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
