# Generated by Django 2.2.7 on 2019-11-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20191111_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='tipo',
            field=models.CharField(blank=True, choices=[('E', 'Estudante'), ('O', 'Orientador')], max_length=100),
        ),
    ]
