# Generated by Django 2.2.7 on 2019-11-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0010_auto_20191126_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='email_autor_1',
            field=models.EmailField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='email_autor_2',
            field=models.EmailField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='email_autor_3',
            field=models.EmailField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='email_orientador_1',
            field=models.EmailField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='email_orientador_2',
            field=models.EmailField(blank=True, default=None, max_length=100),
        ),
    ]
