# Generated by Django 2.2.7 on 2019-11-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_auto_20191111_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='idade',
            field=models.IntegerField(blank=True, verbose_name='Idade'),
        ),
    ]
