# Generated by Django 2.2.7 on 2019-11-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_auto_20191111_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='idade',
            field=models.IntegerField(blank=True, default=None, verbose_name='Idade'),
        ),
    ]
