# Generated by Django 2.2.7 on 2019-11-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_projeto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='user',
        ),
    ]
