# Generated by Django 2.2.7 on 2019-11-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_auto_20191112_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='palavras_chave',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
