# Generated by Django 2.2.7 on 2019-11-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_projeto_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='alteracoes',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
