# Generated by Django 2.2.7 on 2019-11-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_auto_20191112_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='introducao',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='projeto',
            name='material',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='projeto',
            name='metodologia',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='projeto',
            name='objetivos',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='projeto',
            name='referencias_bibliograficas',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='projeto',
            name='resultados',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='autor',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='palavras_chave',
            field=models.CharField(max_length=30),
        ),
    ]
