# Generated by Django 2.2.7 on 2019-11-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0015_projeto_alteracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='status',
            field=models.CharField(default='Aguardando', max_length=100),
        ),
    ]
