# Generated by Django 2.2.7 on 2019-11-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_projeto_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(default='Aguardando Avaliação', max_length=100),
        ),
    ]
