# Generated by Django 2.2.7 on 2019-11-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_auto_20191128_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('AA', 'Aguardando Avaliação'), ('R', 'Rejeitado'), ('A', 'Aceito')], default=('AA', 'Aguardando Avaliação'), max_length=100),
        ),
    ]
