# Generated by Django 2.2.7 on 2019-11-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0021_auto_20191128_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='link_video',
            field=models.URLField(max_length=100),
        ),
    ]
